### ISSUE TITLE
SocketTimeout when client tries to contact socketserver

### ISSUE THREAD

**Issue by pnpranavrao** [DrJukka/MyWifiMesh#2]
Hello @DrJukka!
I've begun to appreciate your detailed experimentation with Wifi/Bluetooth on Android here and on your blog.

When I run this project though, everything works (creation of AP, service discovery etc), but when the client tries to hit the `SocketServer` running on the `GroupOwner`, I've been getting a SocketTimeoutError. 
https://github.com/DrJukka/MyWifiMesh/blob/master/MyWifiMesh/app/src/main/java/test/microsoft/com/mywifimesh/ClientSocketHandler.java#L40

I tried debugging a lot - Do you have any leads as to why this could be happening? 
Thanks in advance!

**Comment by DrJukka** [comment]
I would first suspect that the Listener socket is not accepting connections for some reason

**Comment by pnpranavrao** [comment]
Thanks for getting back!
This was because the phone running the `ClientSocketHandler` would switch to another network(non WifiDirect). After we forced it to use WifiDirect's AP point everything worked as expected.

**Comment by yangster23** [comment]
How did you force the WiFi Direct's AP point? I'm running into the same error! Thanks

**Comment by yangster23** [comment]
I tried to assign the parameter of the IP address of the client socket with the WifiP2pInfo Object that is received on ifConnectIsAvailable() in the AccessPoint class, but I still get the timeout error.... Did you do something different?

**Comment by DrJukka** [comment]
I’m not working on that area currently, thus won’t be able to give too much support really.

Anyway, if you would first try using the codes as provided before making modifications, you might get the idea how they work. i.e. do not mix WifiDirect codes with Accesspoint approaches, if you are doing an access point with wifi direct, your wifi direct connection parts can not be used in there.

Also start by having only two devices communicating, then the possibility them on having same IP address is practically zero.

-jukka-
